export const site = {
  name: "Magic Clean",
  legalName: "Magic Clean Cleaning Services",
  tagline: "House and office cleaning across Cambridgeshire & Huntingdonshire",
  phoneDisplay: "+44 7400 126 612",
  phoneHref: "tel:+447400126612",
  email: "monika.mirga@yahoo.co.uk",
  emailHref: "mailto:monika.mirga@yahoo.co.uk",
  companyAddress: {
    line2: "Peterborough, Cambridgeshire",
    line3: "United Kingdom",
    display: "30 Pheasant Way, Yaxley, Peterborough, Cambridgeshire, United Kingdom",
  },
  area: "Cambridgeshire and Huntingdonshire",
  availability: "Available to start immediately",
  counties: ["Cambridgeshire", "Huntingdonshire", "Peterborough"] as const,
  towns: [
    "Peterborough",
    "Cambridge",
    "Huntingdon",
    "St Neots",
    "Ely",
    "St Ives",
    "March",
    "Wisbech",
  ] as const,
  workStyles: [
    "Weekly regular clean",
    "Fortnightly regular clean",
    "One-off deep clean",
    "Same-day / as soon as possible",
    "Office / commercial schedule",
    "Move-in or move-out clean",
  ] as const,
  nav: [
    { href: "#services", label: "Services" },
    { href: "#results", label: "Results" },
    { href: "#why", label: "Why us" },
    { href: "#areas", label: "Areas" },
    { href: "#contact", label: "Contact" },
  ] as const,
} as const;
